### ISSUE TITLE
Edit Emoji doesn't always work

### ISSUE THREAD

**Issue by worker8** [star-39/moe-sticker-bot#15]
Thanks for the awesome project! 🥇 

I want to report a bug 🐛 .

Here's the step that I have taken:
<img src="https://user-images.githubusercontent.com/1988156/169045009-768e7984-5123-4a63-88db-cce94aff97e6.png" width="300px" />

<img width="300" alt="Screen Shot 2022-05-18 at 22 01 06" src="https://user-images.githubusercontent.com/1988156/169045057-4feff219-0d57-4eb4-acb3-84edc9e37185.png">

But after doing this, the following sticker doesn't get assigned to 👀 . It still remains as the emoji that it was previously assigned.
<img width="212" alt="Screen Shot 2022-05-18 at 22 04 28" src="https://user-images.githubusercontent.com/1988156/169045214-e9ed0c1c-6189-4276-b9de-0623422f7dcb.png">

**Comment by star-39** [comment]
Thank you for reporting!

I will investigate this issue tomorrow.

Since Telegram does not support editing directly through API, current "editing" was done by 

1. Uploading a new sticker with emoji specified.
2. Move the newly uploaded sticker to previous position.
3. Delete the previous sticker.

This step is complex and might result unexpected error(eg. Flood Limit)

I'm planning to optimize these steps.
